// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SwitchUIClient is the client API for SwitchUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SwitchUIClient interface {
	// ListEngineSpecs returns a list of Switching Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (SwitchUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type switchUIClient struct {
	cc grpc.ClientConnInterface
}

func NewSwitchUIClient(cc grpc.ClientConnInterface) SwitchUIClient {
	return &switchUIClient{cc}
}

func (c *switchUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (SwitchUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &SwitchUI_ServiceDesc.Streams[0], "/v1.SwitchUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &switchUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SwitchUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type switchUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *switchUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *switchUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.SwitchUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SwitchUIServer is the server API for SwitchUI service.
// All implementations must embed UnimplementedSwitchUIServer
// for forward compatibility
type SwitchUIServer interface {
	// ListEngineSpecs returns a list of Switching Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, SwitchUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedSwitchUIServer()
}

// UnimplementedSwitchUIServer must be embedded to have forward compatible implementations.
type UnimplementedSwitchUIServer struct {
}

func (UnimplementedSwitchUIServer) ListEngineSpecs(*ListEngineSpecsRequest, SwitchUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedSwitchUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedSwitchUIServer) mustEmbedUnimplementedSwitchUIServer() {}

// UnsafeSwitchUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SwitchUIServer will
// result in compilation errors.
type UnsafeSwitchUIServer interface {
	mustEmbedUnimplementedSwitchUIServer()
}

func RegisterSwitchUIServer(s grpc.ServiceRegistrar, srv SwitchUIServer) {
	s.RegisterService(&SwitchUI_ServiceDesc, srv)
}

func _SwitchUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SwitchUIServer).ListEngineSpecs(m, &switchUIListEngineSpecsServer{stream})
}

type SwitchUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type switchUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *switchUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SwitchUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwitchUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.SwitchUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwitchUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SwitchUI_ServiceDesc is the grpc.ServiceDesc for SwitchUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SwitchUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.SwitchUI",
	HandlerType: (*SwitchUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _SwitchUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _SwitchUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "switch-ui.proto",
}
